import { z } from "zod";
import type { ModuleManifest } from "./manifest.js";

const V = "0.1";
const M3 = ["match3"];

/**
 * match-3 模块库（docs/09 §6.2）。首发 14 + 二批 4。
 * 新增模块 = 往这里加一条 manifest + 写对应实现/参数翻译。
 */
export const ALL_MANIFESTS: ModuleManifest[] = [
  // ---- 首发 14 ----
  {
    id: "board-grid",
    kind: "world",
    genre: ["*"],
    batch: "首发",
    description: "棋盘网格 + 元素类型集，生成无预成匹配的初盘",
    params: z.object({ size: z.tuple([z.number().int().positive(), z.number().int().positive()]), tiles: z.array(z.string()).min(3) }),
    reads: [],
    writes: ["board"],
    deps: [],
    triggers: ["genre:match3"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "board-layer",
    kind: "world",
    genre: M3,
    batch: "首发",
    description: "覆盖层（果冻/冰冻），消除其上元素清层",
    params: z.object({ layer: z.string(), coverage: z.string() }),
    reads: ["board"],
    writes: ["board"],
    deps: ["board-grid"],
    examples: ["candy-crush-jelly-23"],
    schema_version: V,
  },
  {
    id: "input-swap",
    kind: "input",
    genre: M3,
    batch: "首发",
    description: "相邻两格交换；requireMatch 时不成立则弹回",
    params: z.object({ mode: z.literal("adjacent").default("adjacent"), requireMatch: z.boolean().default(true) }),
    reads: ["board", "input"],
    writes: ["board"],
    deps: ["board-grid"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "match-detect",
    kind: "system",
    genre: M3,
    batch: "首发",
    description: "匹配检测：横/竖 ≥ line（形状可选）",
    params: z.object({ line: z.number().int().min(3).default(3), shapes: z.array(z.enum(["line", "L", "T"])).optional(), simultaneous: z.boolean().optional() }),
    reads: ["board"],
    writes: [],
    deps: ["board-grid"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "special-tile",
    kind: "system",
    genre: M3,
    batch: "首发",
    description: "特殊元素生成（4连/5连/LT → 条纹/炸弹/包装）",
    params: z.object({ spawn: z.record(z.string()) }),
    reads: ["board"],
    writes: ["board"],
    deps: ["match-detect"],
    examples: ["candy-crush-jelly-23"],
    schema_version: V,
  },
  {
    id: "special-trigger",
    kind: "system",
    genre: M3,
    batch: "首发",
    description: "特殊元素单个触发效果（条纹消行列/炸弹消同色/包装范围爆）",
    params: z.object({ effects: z.array(z.string()) }),
    reads: ["board"],
    writes: ["board", "score"],
    deps: ["special-tile"],
    examples: ["candy-crush-jelly-23"],
    schema_version: V,
  },
  {
    id: "clear-resolve",
    kind: "system",
    genre: M3,
    batch: "首发",
    description: "消除被匹配元素（可连带清覆盖层）",
    params: z.object({ clearsLayer: z.string().optional() }),
    reads: ["board"],
    writes: ["board"],
    deps: ["match-detect"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "gravity-fall",
    kind: "system",
    genre: ["*"],
    batch: "首发",
    description: "重力下落填补空位",
    params: z.object({ speed: z.number().positive().default(800) }),
    reads: ["board"],
    writes: ["board"],
    deps: ["clear-resolve"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "refill-spawn",
    kind: "system",
    genre: ["*"],
    batch: "首发",
    description: "顶部补充新元素",
    params: z.object({ from: z.literal("top").default("top"), weight: z.enum(["even", "weighted"]).default("even") }),
    reads: ["board"],
    writes: ["board"],
    deps: ["gravity-fall"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "cascade",
    kind: "system",
    genre: M3,
    batch: "首发",
    description: "连锁：消除后再检测 → 连击",
    params: z.object({ combo: z.boolean().default(true) }),
    reads: ["board"],
    writes: ["score"],
    deps: ["match-detect", "refill-spawn"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "score-combo",
    kind: "system",
    genre: ["*"],
    batch: "首发",
    description: "计分 + 连击倍率",
    params: z.object({ base: z.number().default(10), comboMult: z.number().default(1.5) }),
    reads: ["board"],
    writes: ["score"],
    deps: ["clear-resolve"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "goal-tracker",
    kind: "goal",
    genre: M3,
    batch: "首发",
    description: "多类型目标 → 胜负（collect/score/clearLayer/drop）",
    params: z.object({
      collect: z.record(z.number()).optional(),
      score: z.union([z.number(), z.literal("endless")]).optional(),
      clearLayer: z.string().optional(),
      drop: z.object({ item: z.string(), count: z.number() }).optional(),
    }),
    reads: ["board", "score"],
    writes: ["status"],
    deps: [],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  {
    id: "move-budget",
    kind: "system",
    genre: ["*"],
    batch: "首发",
    description: "步数 / 计时限制",
    params: z.object({ moves: z.number().int().positive().optional(), time: z.number().positive().optional() }),
    reads: [],
    writes: ["status"],
    deps: [],
    examples: ["candy-collect"],
    schema_version: V,
  },
  {
    id: "shuffle-deadlock",
    kind: "system",
    genre: M3,
    batch: "首发",
    description: "无解检测 + 重洗/结束",
    params: z.object({ onDeadlock: z.enum(["shuffle", "end"]).default("shuffle") }),
    reads: ["board"],
    writes: ["board", "status"],
    deps: ["match-detect"],
    examples: ["bejeweled-classic", "candy-collect"],
    schema_version: V,
  },
  // ---- 二批 4 ----
  {
    id: "input-link",
    kind: "input",
    genre: M3,
    batch: "二批",
    description: "同色连线（连连看 / Two Dots 式）",
    params: z.object({ match: z.literal("same-color").default("same-color") }),
    reads: ["board", "input"],
    writes: ["board"],
    deps: ["board-grid"],
    examples: ["two-dots"],
    schema_version: V,
  },
  {
    id: "input-drag-path",
    kind: "input",
    genre: M3,
    batch: "二批",
    description: "限时拖拽自由移动（PAD 式）",
    params: z.object({ duration: z.number().positive() }),
    reads: ["board", "input"],
    writes: ["board"],
    deps: ["board-grid"],
    examples: ["pad-dungeon"],
    schema_version: V,
  },
  {
    id: "spreader",
    kind: "system",
    genre: M3,
    batch: "二批",
    description: "蔓延阻挡物（巧克力/藤蔓），相邻消除阻止",
    params: z.object({ target: z.string(), perTurn: z.number().int().positive().default(1), blockedByAdjacentClear: z.boolean().default(true) }),
    reads: ["board"],
    writes: ["board"],
    deps: ["board-grid"],
    examples: ["candy-crush-jelly-23"],
    schema_version: V,
  },
  {
    id: "drop-collect",
    kind: "system",
    genre: M3,
    batch: "二批",
    description: "掉落物收集目标（樱桃落底）",
    params: z.object({ item: z.string(), count: z.number().int().positive() }),
    reads: ["board"],
    writes: ["status"],
    deps: ["gravity-fall"],
    examples: ["candy-ingredients"],
    schema_version: V,
  },
];

export const MANIFEST_BY_ID: Map<string, ModuleManifest> = new Map(ALL_MANIFESTS.map((m) => [m.id, m]));
