/* AUTO-GENERATED by scripts/bundle-shared.mjs — do not edit */

var cqShared = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // scripts/shared-entry.ts
  var shared_entry_exports = {};
  __export(shared_entry_exports, {
    assetUrls: () => assetUrls,
    bindingFor: () => bindingFor,
    deriveBaseline: () => deriveBaseline,
    deriveStageEmotes: () => deriveStageEmotes,
    diffState: () => diffState,
    emote: () => emote,
    emoteEnd: () => emoteEnd,
    initialView: () => initialView,
    lifecycle: () => lifecycle,
    parseSseEvents: () => parseSseEvents,
    reduce: () => reduce
  });

  // ../web/src/sse.ts
  function parseSseEvents(buffer) {
    var _a;
    const events = [];
    const parts = buffer.split("\n\n");
    const rest = (_a = parts.pop()) != null ? _a : "";
    for (const block of parts) {
      let event = "message";
      const dataLines = [];
      for (const line of block.split("\n")) {
        if (line.startsWith("event:")) event = line.slice(6).trim();
        else if (line.startsWith("data:")) dataLines.push(line.slice(5).trim());
      }
      if (dataLines.length === 0) continue;
      try {
        events.push({ event, data: JSON.parse(dataLines.join("\n")) });
      } catch (e) {
      }
    }
    return { events, rest };
  }

  // ../../packages/avatar/src/states.ts
  var EMOTE_PRIORITY = {
    synthesis: 100,
    "build-success": 95,
    error: 90,
    "build-fail": 88,
    "stage-up": 80,
    handoff: 78,
    "constitution-lock": 70,
    "risk-flag": 60,
    "cut-scope": 55,
    "parse-warning": 50,
    stuck: 48,
    "spark-caught": 40,
    "deep-love": 38,
    "hot-signature": 36,
    "emotion-resonance": 30,
    confirm: 25,
    "curious-probe": 20,
    "idea-feed": 15
  };
  var MAJOR_EMOTES = /* @__PURE__ */ new Set([
    "synthesis",
    "error",
    "build-success",
    "build-fail"
  ]);
  function isMajorEmote(e) {
    return MAJOR_EMOTES.has(e);
  }
  function emotePriority(e) {
    return EMOTE_PRIORITY[e];
  }

  // ../../packages/avatar/src/signals.ts
  var lifecycle = (baseline) => ({ kind: "lifecycle", baseline });
  var emote = (e) => ({ kind: "emote", emote: e });
  var emoteEnd = () => ({ kind: "emote-end" });

  // ../../packages/avatar/src/machine.ts
  function initialView(baseline = "idle") {
    return { baseline, emote: null, queue: [] };
  }
  var MAX_QUEUE = 1;
  function enqueue(view, e) {
    if (isMajorEmote(e)) return { ...view, emote: e, queue: [] };
    if (view.emote === null) return { ...view, emote: e };
    const merged = [...view.queue, e].filter((x, i, arr) => arr.indexOf(x) === i && x !== view.emote).sort((a, b) => emotePriority(b) - emotePriority(a)).slice(0, MAX_QUEUE);
    return { ...view, queue: merged };
  }
  function advanceQueue(view) {
    const [next, ...rest] = view.queue;
    return { ...view, emote: next != null ? next : null, queue: rest };
  }
  function reduce(view, signal) {
    switch (signal.kind) {
      case "lifecycle":
        return { ...view, baseline: signal.baseline };
      case "emote":
        return enqueue(view, signal.emote);
      case "emote-end":
        return advanceQueue(view);
    }
  }

  // ../../packages/avatar/src/diffState.ts
  var nonEmpty = (v) => Boolean(v && v.trim());
  var filled = (a, b) => !nonEmpty(a) && nonEmpty(b);
  var grew = (a, b) => {
    var _a, _b;
    return ((_a = b == null ? void 0 : b.length) != null ? _a : 0) > ((_b = a == null ? void 0 : a.length) != null ? _b : 0);
  };
  function diffState(prev, next) {
    var _a, _b, _c, _d, _e, _f;
    const out = [];
    if (filled(prev.spark, next.spark) || grew(prev.references, next.references)) out.push("spark-caught");
    if (filled(prev.coreEmotion, next.coreEmotion) || filled(prev.coreFantasy, next.coreFantasy))
      out.push("emotion-resonance");
    if (filled(prev.coreExperience, next.coreExperience) || grew((_a = prev.keywordPools) == null ? void 0 : _a.emotion, (_b = next.keywordPools) == null ? void 0 : _b.emotion))
      out.push("deep-love");
    if (filled(prev.coreAction, next.coreAction)) out.push("confirm");
    if (grew(prev.juice, next.juice) || grew((_c = prev.engineering) == null ? void 0 : _c.signatureTerms, (_d = next.engineering) == null ? void 0 : _d.signatureTerms))
      out.push("hot-signature");
    if (grew(prev.risks, next.risks)) out.push("risk-flag");
    if (grew((_e = prev.mvpScope) == null ? void 0 : _e.cut, (_f = next.mvpScope) == null ? void 0 : _f.cut)) out.push("cut-scope");
    if (grew(prev.constitution, next.constitution)) out.push("constitution-lock");
    return out.sort((a, b) => emotePriority(b) - emotePriority(a));
  }

  // ../../packages/avatar/src/manifest.ts
  var BASELINE_BINDINGS = {
    idle: { primitive: "calm", loop: true },
    listening: { primitive: "watching", loop: true },
    thinking: { primitive: "thinking", loop: true },
    speaking: { primitive: "talking", loop: true },
    building: { primitive: "flex", loop: true }
  };
  var EMOTE_BINDINGS = {
    "spark-caught": { primitive: "starstruck", loop: false },
    "emotion-resonance": { primitive: "warm-hug", loop: false },
    "deep-love": { primitive: "love", loop: false },
    "curious-probe": { primitive: "inspect", loop: false },
    "idea-feed": { primitive: "point", loop: false },
    confirm: { primitive: "ok", loop: false },
    "hot-signature": { primitive: "fire", loop: false },
    "stage-up": { primitive: "clap", loop: false },
    "constitution-lock": { primitive: "seal", loop: false },
    synthesis: { primitive: "party", loop: false },
    "risk-flag": { primitive: "grimace", loop: false },
    "cut-scope": { primitive: "no-gesture", loop: false },
    "parse-warning": { primitive: "shrug", loop: false },
    error: { primitive: "facepalm", loop: false },
    stuck: { primitive: "persevere", loop: false },
    handoff: { primitive: "wave", loop: false },
    "build-success": { primitive: "raise", loop: false },
    "build-fail": { primitive: "bandage", loop: false }
  };
  var STATE_PRIMITIVE = {
    ...BASELINE_BINDINGS,
    ...EMOTE_BINDINGS
  };
  function bindingFor(state) {
    return STATE_PRIMITIVE[state];
  }
  function assetUrls(primitive, base = "/avatar") {
    const b = base.replace(/\/$/, "");
    return {
      webm: `${b}/${primitive}.webm`,
      hevc: `${b}/${primitive}.mov`,
      poster: `${b}/${primitive}.png`
    };
  }

  // ../web/src/avatar/derive.ts
  function deriveBaseline(input) {
    if (input.busy) {
      return input.lastRole === "assistant" && input.lastContentLen > 0 ? "speaking" : "thinking";
    }
    if (input.typing) return "listening";
    return "idle";
  }
  function deriveStageEmotes(prevStage, nextStage) {
    return prevStage !== null && nextStage > prevStage ? ["stage-up"] : [];
  }
  return __toCommonJS(shared_entry_exports);
})();
module.exports = cqShared;

